In [1]:
import pandas as pd

In [2]:
train = pd.read_csv("../data/train.csv")
test = pd.read_csv("../data/test.csv")

In [7]:
train.head()

,ID,Customer_Birthyear,Customer_Gender,Customer_personal_identifier,Customer_identification_number,Customer_registration_datetime,Customer_credit_rating,Customer_flag_change_of_authentication_1,Customer_flag_change_of_authentication_2,Customer_flag_change_of_authentication_3,...,Last_atm_transaction_datetime,Last_bank_branch_transaction_datetime,Flag_deposit_more_than_tenMillion,Unused_account_status,Recipient_account_suspend_status,Number_of_transaction_with_the_account,Transaction_history_with_the_account,First_time_iOS_by_vulnerable_user,Fraud_Type,Transaction_resumed_date
0,TRAIN_000000,1980,male,이상호,BJWQxd-WBASPLJ,2003-01-06 18:38:01,B,0,1,0,...,2003-01-22 23:38:48,2003-01-22 23:38:48,1,1,1,0,0,0,m,2003-01-22 23:38:48
1,TRAIN_000001,1964,male,박상철,kurCwX-odPUXEt,2003-01-07 16:40:44,C,0,1,0,...,2003-01-21 21:29:08,2003-01-31 00:19:46,0,1,0,0,0,0,m,2003-01-19 21:29:08
2,TRAIN_000002,1982,female,조옥자,OiERQa-CTXBoaX,2003-01-11 14:08:36,B,1,1,0,...,2003-01-31 07:13:28,2003-01-31 07:13:28,0,0,1,1,1,0,m,2003-01-31 07:13:28
3,TRAIN_000003,1982,female,조옥자,OiERQa-CTXBoaX,2003-01-11 14:08:36,B,1,1,1,...,2003-01-31 11:49:56,2003-01-31 07:13:28,1,1,0,0,0,0,m,2003-01-31 07:13:28
4,TRAIN_000004,1982,female,조옥자,OiERQa-CTXBoaX,2003-01-11 14:08:36,B,1,1,1,...,2003-01-31 11:49:56,2003-01-31 07:13:28,1,0,0,1,1,0,m,2003-01-31 07:13:28

In [13]:
for col in train.columns:
    print(f"## {col}")
    print("     unique length : ", len(train[col].unique()))

## ID
     unique length :  120000
## Customer_Birthyear
     unique length :  55
## Customer_Gender
     unique length :  2
## Customer_personal_identifier
     unique length :  1769
## Customer_identification_number
     unique length :  4101
## Customer_registration_datetime
     unique length :  4101
## Customer_credit_rating
     unique length :  6
## Customer_flag_change_of_authentication_1
     unique length :  2
## Customer_flag_change_of_authentication_2
     unique length :  2
## Customer_flag_change_of_authentication_3
     unique length :  2
## Customer_flag_change_of_authentication_4
     unique length :  2
## Customer_rooting_jailbreak_indicator
     unique length :  2
## Customer_mobile_roaming_indicator
     unique length :  2
## Customer_VPN_Indicator
     unique length :  2
## Customer_loan_type
     unique length :  5
## Customer_flag_terminal_malicious_behavior_1
     unique length :  2
## Customer_flag_terminal_malicious_behavior_2
     unique length :  2
## Customer_flag_terminal_malicious_behavior_3
     unique length :  2
## Customer_flag_terminal_malicious_behavior_4
     unique length :  2
## Customer_flag_terminal_malicious_behavior_5
     unique length :  2
## Customer_flag_terminal_malicious_behavior_6
     unique length :  2
## Customer_inquery_atm_limit
     unique length :  2
## Customer_increase_atm_limit
     unique length :  2
## Account_account_number
     unique length :  4101
## Account_account_type
     unique length :  4
## Account_creation_datetime
     unique length :  4101
## Account_initial_balance
     unique length :  86700
## Account_balance
     unique length :  102862
## Account_indicator_release_limit_excess
     unique length :  2
## Account_amount_daily_limit
     unique length :  4
## Account_indicator_Openbanking
     unique length :  2
## Account_remaining_amount_daily_limit_exceeded
     unique length :  3030
## Account_release_suspention
     unique length :  2
## Account_one_month_max_amount
     unique length :  15880
## Account_one_month_std_dev
     unique length :  68452
## Account_dawn_one_month_max_amount
     unique length :  8466
## Account_dawn_one_month_std_dev
     unique length :  28101
## Transaction_Datetime
     unique length :  119995
## Transaction_Amount
     unique length :  11409
## Channel
     unique length :  4
## Operating_System
     unique length :  6
## Error_Code
     unique length :  2
## Transaction_Failure_Status
     unique length :  2
## Type_General_Automatic
     unique length :  2
## IP_Address
     unique length :  119996
## MAC_Address
     unique length :  101500
## Access_Medium
     unique length :  7
## Location
     unique length :  18556
## Recipient_Account_Number
     unique length :  49815
## Transaction_num_connection_failure
     unique length :  6
## Another_Person_Account
     unique length :  1
## Distance
     unique length :  119943
## Time_difference
     unique length :  57507
## Unused_terminal_status
     unique length :  2
## Last_atm_transaction_datetime
     unique length :  82592
## Last_bank_branch_transaction_datetime
     unique length :  83409
## Flag_deposit_more_than_tenMillion
     unique length :  2
## Unused_account_status
     unique length :  2
## Recipient_account_suspend_status
     unique length :  2
## Number_of_transaction_with_the_account
     unique length :  11
## Transaction_history_with_the_account
     unique length :  18
## First_time_iOS_by_vulnerable_user
     unique length :  2
## Fraud_Type
     unique length :  13
## Transaction_resumed_date
     unique length :  56200

In [9]:
len(train["ID"].unique())

120000

In [8]:
len(train["Customer_personal_identifier"].unique())

1769

In [10]:
len(train["Customer_identification_number"].unique())

4101

In [11]:
len(train["Customer_registration_datetime"].unique())

4101